### PR TITLE
Aggregation of Select Surveys as well as proper deletion

### PR DESCRIPTION
**Pull request by philippzagar**
# *Aggregation of Select Surveys as well as proper deletion*

## :recycle: Current situation & Problem
Aggregation of Select Surveys not possible, leftover survey data in database even after deletion

## :bulb: Proposed solution
Aggregation of Select Surveys as well as proper deletion

## :heavy_plus_sign: Additional Information
https://github.com/TUM4Health/data-management-service/blob/a0275452da1716a24331d47ecbb3950f44556721/src/api/survey-response-select-accumulated/routes/survey-response-select-accumulated.js#L2-L22

Here u can see the routes, both require `surveyId` as an URL parameter, so something like `http://localhost:1337/api/survey-select-delete?surveyId=13`. However, note that this `surveyId` references to the ID of the `survey_question_selects` relation, so the ID of the Survey Select question.

Both routes:
- `http://localhost:1337/api/survey-select-delete?surveyId=13`
    -  Deleted all associated data to a survey selection question ID
- `http://localhost:1337/api/survey-response-select-accumulated?surveyId=1`
    - Fetch an accumulated result of a survey selection question ID

### Related PRs
None

### Testing
Testing is the responsibility of the user

### Reviewer Nudging
Take a look at `src/api/survey-response-select-accumulated/controllers/survey-response-select-accumulated.js`, there basically all the logic lies

### CODE REVIEW

**Comment by Bentipa** [comment]
`Error: next() called multiple times
    at dispatch (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/koa-compose/index.js:36:45)
    at Object.fetchAccumulatedSurveySelects (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/src/api/survey-response-select-accumulated/controllers/survey-response-select-accumulated.js:41:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async returnBodyMiddleware (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/middlewares/body.js:25:7
    at async /home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@koa/cors/index.js:56:32)
    at async /home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/koa-session/index.js:41:7)
    at async /home/benjamin/Documents/Projects/Uni/TUM4Health/data-management-service/node_modules/@strapi/strapi/lib/services/metrics/middleware.js:29:5`

pls fix (error occurs on call without error response, so works)

**Comment by Bentipa** [comment]
https://docs.strapi.io/developer-docs/latest/development/backend-customization/models.html#hook-event-object

could you use this one to just delete the full select tree?
I guess this also applies for the other types (so include the responses).
Then I can just call the regular delete on the survey question itself

**Comment by philippzagar** [comment]
@Bentipa 
Deletes can now be done on the regular `survey-question` route (via lifecycle hooks, thx for the hint), it cleans up questions, selects choices, responses etc. for all survey types (no code adaptions necessary in client).
The aggregation code error should be fixed as well.

**Comment by philippzagar** [comment]
@Bentipa

**Comment by Bentipa** [comment]
ja jetzt merge den schmarn halt 😂 ich tests wenn ich zeit hab

**Comment by philippzagar** [comment]
eiei immer diese manager 😂

**Pull request merged**
